### ISSUE TITLE
Ruler support for '-n' load annotations

### ISSUE THREAD

**Issue by brad-t-moore** [KitwareMedical/ImageViewer#118]
Currently only the Box annotation is supported by ImageViewer for loading annotations.  Add support for Ruler annotations (note, the export of Ruler annotations currently works).

See: https://github.com/KitwareMedical/ImageViewer/blob/db6c8b40e370fec17812835de80c665c0ef4a6d9/QtImageViewer/QtImageViewer.cxx#L324-L372

**Comment by tao558** [comment]
> @tao558 Tom, do you have any cycles to look into this? Sean might have the entire healthy volunteer dataset done this week and this could help with getting at the ONSD reliability.

Sure
