### ISSUE TITLE
On windows, inner build is not rebuilt by superbuild

### ISSUE THREAD

**Issue by finetjul** [KitwareMedical/ImageViewer#26]
When an inner build CMakeLists.txt file is edited (e.g. ImageViewer/CMakeLists.txt), a build in the superbuild project does not do anything to the inner build . The inner build is not reconfigured nor built.

**Comment by aylward** [comment]
Agreed.  This is one of the many challenges with using superbuild.  For this and other reasons we have discontinued the use of superbuild in ImageViewer.   It now follows a more traditional build directory structure and encourages the use of shared, external ITK builds.
